# The pieces Kubernetes cannot hold: the database, the secret containers, and
# the two names that point at the ingress. Everything else is deploy/base.
#
# AWS because it is the likeliest target, not because anything in the app is
# tied to it — swap aws_db_instance for the managed Postgres of another cloud
# and the rest of the kit does not notice. What it does need is Postgres 15+
# with pgvector available, which every managed Postgres worth using now has.

locals {
  tags = merge(var.tags, {
    "app.kubernetes.io/name" = "ragkit"
    ManagedBy                = "terraform"
  })
}

# --- Postgres ----------------------------------------------------------------

resource "aws_db_instance" "postgres" {
  identifier     = "${var.name_prefix}-postgres"
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  db_name  = var.database_name
  username = var.master_username

  # The password is generated by RDS, stored in a Secrets Manager secret RDS
  # owns, and rotated there. The alternative — random_password, or a var — puts
  # the production database password in Terraform state in plaintext, where
  # everyone with read access to the state bucket has it forever.
  manage_master_user_password   = true
  master_user_secret_kms_key_id = var.kms_key_id

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = var.kms_key_id

  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids = var.vpc_security_group_ids
  publicly_accessible    = false

  multi_az                = var.multi_az
  backup_retention_period = var.backup_retention_period
  copy_tags_to_snapshot   = true

  # Postgres logs go where the app's logs go. `GET /audit/verify` catches edits
  # made through the app's own connection; the server log is where a change
  # made around it leaves a trace (docs/security.md).
  enabled_cloudwatch_logs_exports = ["postgresql"]

  deletion_protection = var.deletion_protection

  # A fixed name, so a second destroy in the same account collides loudly
  # instead of quietly overwriting the snapshot of the first one.
  skip_final_snapshot       = false
  final_snapshot_identifier = "${var.name_prefix}-postgres-final"

  # No parameter group and no CREATE EXTENSION here. `CREATE EXTENSION IF NOT
  # EXISTS vector` is the first statement of the first Alembic migration
  # (13e754f2ef3c), so the migration Job enables pgvector on the way in. Doing
  # it from Terraform would mean a postgresql provider with a live route to a
  # private subnet, for one statement the app already owns.

  tags = local.tags
}

# --- Secrets -----------------------------------------------------------------

# Container only, deliberately versionless. No aws_secretsmanager_secret_version
# anywhere in this module: a version resource takes the value as an argument,
# and every argument Terraform sees ends up in state. The values are written
# once, out of band:
#
#   aws secretsmanager put-secret-value --secret-id ragkit/app \
#     --secret-string "$(jq -n --arg j "$(openssl rand -hex 32)" --arg k "$KEY" \
#        '{JWT_SECRET:$j, OPENAI_API_KEY:$k}')"
#
# Terraform owns the container, its policy and its lifecycle; it never learns
# the contents. `terraform plan` stays clean because the value is not tracked.
resource "aws_secretsmanager_secret" "app" {
  name        = "${var.name_prefix}/app"
  description = "JWT_SECRET and OPENAI_API_KEY for the ragkit-secrets Kubernetes Secret. Values are set out of band; Terraform never reads them."
  kms_key_id  = var.kms_key_id
  tags        = local.tags
}

# --- DNS ---------------------------------------------------------------------

# CNAME, not an alias: an alias record needs the load balancer's hosted zone id,
# and the load balancer is created by the ingress controller after this module
# runs. A CNAME needs only the hostname `kubectl get ingress` prints. The cost
# is that neither name may be the zone apex.
resource "aws_route53_record" "app" {
  zone_id = var.route53_zone_id
  name    = var.app_hostname
  type    = "CNAME"
  ttl     = var.dns_ttl
  records = [var.ingress_hostname]
}

resource "aws_route53_record" "api" {
  zone_id = var.route53_zone_id
  name    = var.api_hostname
  type    = "CNAME"
  ttl     = var.dns_ttl
  records = [var.ingress_hostname]
}
